### ISSUE TITLE
Failed to download source code 

### ISSUE THREAD

**Issue by nithin-nk** [Azure/acr-build#14]
I am trying to build ACR image with the following code

```
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
            service_principal: ${{ secrets.service_principal }}
            service_principal_password: ${{ secrets.service_principal_password }}
            tenant: ${{ secrets.tenant }}
            registry: ${{ secrets.registry }}
            repository: ${{ secrets.repository }}
            image: flink-image
            git_access_token: ${{ secrets.git_access_token }}
            folder: ./deployments
            branch: main
            tag: ${{ github.sha }}
            dockerfile: ./deployments/Dockerfile
```
I am getting the below mentioned error

Downloading source code... 45 Run ID: cb8 failed after 3s. Error: failed to download context. Please check if the URL is incorrect. If it has credentials, please check if they are expired

I am not using any URL in configuration

Kindly help
