### ISSUE TITLE
entrypoint.sh: line 9: jq: command not found

### ISSUE THREAD

**Issue by foxt** [Azure/acr-build#19]
The `mcr.microsoft.com/azure-cli` image on versions greater than 2.63.0 use Azure Linux (cbl-mariner2.0) instead of Alpine. It seems that during this change 'jq' was removed from the image, which causes `azure/acr-build` to fail as it expects `jq` to be present in the image.

```
Run azure/acr-build@v1
  with:
    service_principal: ***
    service_principal_password: ***
    tenant: ***
    registry: ***
    repository: ***
    image: ***
    dockerfile: ./docker/Dockerfile
    folder: ./
    branch: main
    tag: ***
    git_access_token: ***
    build_args: ***
  env:
    APP_VERSION: 4.2.0-4b4e5a3
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_1725368581532
    KUBE_CONFIG_PATH: /home/runner/work/_temp/kubeconfig_1725368581532
/usr/bin/docker run --name ee8bc512aefa49444ea92df17e6e7be1759_041e7f --label 716ee8 --workdir /github/workspace --rm -e "APP_VERSION" -e "AZURE_HTTP_USER_AGENT" -e "AZUREPS_HOST_ENVIRONMENT" -e "KUBECONFIG" -e "KUBE_CONFIG_PATH" -e "INPUT_SERVICE_PRINCIPAL" -e "INPUT_SERVICE_PRINCIPAL_PASSWORD" -e "INPUT_TENANT" -e "INPUT_REGISTRY" -e "INPUT_REPOSITORY" -e "INPUT_IMAGE" -e "INPUT_DOCKERFILE" -e "INPUT_FOLDER" -e "INPUT_BRANCH" -e "INPUT_TAG" -e "INPUT_GIT_ACCESS_TOKEN" -e "INPUT_BUILD_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_RE
/entrypoint.sh: line 9: jq: command not found
````
